source 'https://rubygems.org'

gem 'grpc', '~> 1.50'
gem 'grpc-tools', '~> 1.50'

# Ensure we use the same version of protocol buffers
gem 'google-protobuf', '~> 3.21'

# For pretty printing
gem 'colorize', '~> 0.8.1' 