require_relative 'test_service_services_pb'  # generated by grpc_tools_ruby_protoc

class TestServiceImpl < Test::TestService::Service
  def unary_echo(req, _unused_call)
    Test::EchoResponse.new(message: req.message)
  end

  def client_stream(stream, _call)
    msgs = stream.map(&:message)
    Test::StreamResponse.new(messages: msgs)
  end

  def server_stream(req, _call)
    Enumerator.new do |y|
      req.message.each_char { |c| y << Test::StreamResponse.new(messages: [c]) }
    end
  end

  def bidi_stream(stream, _call)
    Enumerator.new do |y|
      stream.each { |req| y << Test::EchoResponse.new(message: req.message.upcase) }
    end
  end
end
