# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_service.proto

require 'google/protobuf'


descriptor_data = "\n\x12test_service.proto\x12\x04test\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rStreamRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0eStreamResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2\xfa\x01\n\x0bTestService\x12\x34\n\tUnaryEcho\x12\x11.test.EchoRequest\x1a\x12.test.EchoResponse\"\x00\x12=\n\x0c\x43lientStream\x12\x13.test.StreamRequest\x1a\x14.test.StreamResponse\"\x00(\x01\x12;\n\x0cServerStream\x12\x11.test.EchoRequest\x1a\x14.test.StreamResponse\"\x00\x30\x01\x12\x39\n\nBidiStream\x12\x11.test.EchoRequest\x1a\x12.test.EchoResponse\"\x00(\x01\x30\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Test
  EchoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.EchoRequest").msgclass
  EchoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.EchoResponse").msgclass
  StreamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.StreamRequest").msgclass
  StreamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.StreamResponse").msgclass
end
