# frozen_string_literal: true

require "bundler/gem_tasks"
require "minitest/test_task"

SMOKE_TEST_GLOBS = %w[
  test/options/bind.rb
  test/options/header_read_timeout.rb
  test/options/test_request_timeout.rb
  test/options/test_threads.rb
  test/rack/test_rack_server.rb
  test/middleware/allow_list.rb
  test/middleware/auth_api_key.rb
  test/middleware/auth_basic.rb
  test/middleware/cache_control.rb
  test/middleware/cidr_to_regex.rb
  test/middleware/compression.rb
  test/middleware/cors.rb
  test/middleware/csp.rb
  test/middleware/deny_list.rb
  test/middleware/etag.rb
  test/middleware/header_interpolation.rb
  test/middleware/location.rb
  test/middleware/max_body.rb
  test/middleware/request_headers.rb
  test/middleware/response_headers.rb
  test/middleware/static_assets.rb
  test/middleware/static_response.rb
  test/middleware/string_rewrite.rb
].freeze

def configure_test_task(task_name, test_globs)
  Minitest::TestTask.create(task_name) do |t|
    t.libs << "test"
    t.libs << "lib"
    t.warning = false
    t.test_globs = test_globs
    t.test_prelude = 'require "helpers/test_helper.rb"'
  end
end

configure_test_task(:test, ["test/**/*.rb"])
configure_test_task("test:smoke", SMOKE_TEST_GLOBS)

task "test:full" => :test

require "rb_sys/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("itsi-server.gemspec")

RbSys::ExtensionTask.new("itsi-server", GEMSPEC) do |ext|
  ext.lib_dir = "lib/itsi/server"
end

task default: %i[compile test rubocop]
