# frozen_string_literal: true

require "bundler/gem_tasks"
require "minitest/test_task"


Minitest::TestTask.create(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.warning = false
  t.test_globs = ['test/**/*.rb']
  t.test_prelude = 'require "helpers/test_helper.rb"'
end

require "rubocop/rake_task"

RuboCop::RakeTask.new

require "rb_sys/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("itsi-server.gemspec")

RbSys::ExtensionTask.new("itsi-server", GEMSPEC) do |ext|
  ext.lib_dir = "lib/itsi/server"
end

task default: %i[compile test rubocop]
