# frozen_string_literal: true

require "bundler/gem_tasks"
require "minitest/test_task"

def configure_test_task(task_name, test_globs)
  Minitest::TestTask.create(task_name) do |t|
    t.libs << "test"
    t.libs << "lib"
    t.warning = false
    t.test_globs = test_globs
    t.test_prelude = 'require "helpers/test_helper.rb"'
  end
end

configure_test_task(:test, ["test/**/*.rb"])
configure_test_task("test:smoke", Dir["test/**/*.rb"].reject do |path|
  path.start_with?("test/helpers/") || %w[
    test/middleware/intrusion_protection.rb
    test/middleware/rate_limit.rb
  ].include?(path)
end)

task "test:full" => :test

require "rb_sys/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("itsi-server.gemspec")

RbSys::ExtensionTask.new("itsi-server", GEMSPEC) do |ext|
  ext.lib_dir = "lib/itsi/server"
end

task default: %i[compile test rubocop]
