# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: echo.proto for package 'echo'

require 'grpc'
require_relative 'echo_pb'

module Echo
  module EchoService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'echo.EchoService'

      # Simple unary method
      rpc :Echo, ::Echo::EchoRequest, ::Echo::EchoResponse
      # Server streaming method
      rpc :EchoStream, ::Echo::EchoRequest, stream(::Echo::EchoResponse)
      # Client streaming method
      rpc :EchoCollect, stream(::Echo::EchoRequest), ::Echo::EchoResponse
      # Bidirectional streaming method
      rpc :EchoBidirectional, stream(::Echo::EchoRequest), stream(::Echo::EchoResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
