# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "itsi-server", path: "../../gems/server"
gem "itsi-scheduler", path: "../../gems/scheduler"

gem 'unicorn'
gem 'pitchfork'
gem 'async'
gem 'falcon'
gem 'agoo'
gem 'iodine'
gem 'debug'
gem 'pry-byebug'
