source "https://rubygems.org"

gemspec

group :development, :test do
  gem "bundler"
  gem "activerecord"
  gem "minitest", "~> 5.16"
  gem "minitest-reporters"
  gem "pg"
  gem "rake", "~> 13.0"
  gem "rake-compiler"
  gem "rb_sys", "~> 0.9.91"
end
