# frozen_string_literal: true

require "bundler/gem_tasks"
require "minitest/test_task"

SMOKE_TEST_GLOBS = %w[
  test/test_itsi_scheduler.rb
  test/test_kernel_sleep.rb
  test/test_block_unblock.rb
  test/test_network_io.rb
  test/test_address_resolve.rb
  test/test_file_io.rb
  test/test_process_wait.rb
].freeze

def configure_test_task(task_name, test_globs)
  Minitest::TestTask.create(task_name) do |t|
    t.libs << "test"
    t.libs << "lib"
    t.warning = false
    t.test_globs = test_globs
    t.test_prelude = 'require "helpers/test_helper.rb"'
  end
end

configure_test_task(:test, ["test/**/*.rb"])
configure_test_task("test:smoke", SMOKE_TEST_GLOBS)

task "test:full" => :test

require "rb_sys/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("itsi-scheduler.gemspec")

RbSys::ExtensionTask.new("itsi-scheduler", GEMSPEC) do |ext|
  ext.lib_dir = "lib/itsi/scheduler"
end

task default: %i[compile test rubocop]
