# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: echo.proto for package 'echo'

require 'grpc'
require_relative 'echo_pb'

module Echo
  module EchoService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'echo.EchoService'

      rpc :Echo, ::Echo::EchoRequest, ::Echo::EchoResponse
    end

    Stub = Service.rpc_stub_class
  end
end
