# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

# gem 'debug'
gem 'grpc'
gem 'itsi-scheduler', path: '../../gems/scheduler'
gem 'itsi-server', path: '../../gems/server'
gem 'rubocop'
gem 'ruby-lsp'
gem 'debug'
